/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type Overlay = {
  image?: OverlayImage;
  width?: number;
  height?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type OverlayImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "overlay.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  hero?: Localized;
  cta?: Localized;
  ctaSecondary?: Localized;
  processIntro?: Localized;
  processSubline?: Localized;
  callUrl?: string;
  whatsappUrl?: string;
  youtubeUrl?: string;
  toolsUrl?: string;
  email?: string;
  socials?: Array<{
    title?: string;
    url?: string;
    _key: string;
  }>;
  clients?: Array<{
    name?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  videos?: Array<{
    title?: Localized;
    url?: string;
    _key: string;
  }>;
  defaultSeo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: Localized;
  description?: Localized;
  ogTitle?: Localized;
  ogDescription?: Localized;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonical?: string;
  noIndex?: boolean;
};

export type Localized = {
  _type: "localized";
  fr?: string;
  en?: string;
  es?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Offer = {
  _id: string;
  _type: "offer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  price?: string;
  promise?: Localized;
  description?: Localized;
  weeks?: string;
  includes?: Array<
    {
      _key: string;
    } & Localized
  >;
  media?: Media;
  order?: number;
};

export type Media = {
  _type: "media";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: Localized;
  frameWidth?: number;
  frameHeight?: number;
  background?: string;
  crop?: string;
  embedSearch?: boolean;
  overlay?: Overlay;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  person?: string;
  company?: string;
  role?: Localized;
  quote?: Localized;
  media?: Media;
  order?: number;
};

export type ProcessStep = {
  _id: string;
  _type: "processStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Localized;
  summary?: Localized;
  description?: Localized;
  time?: Localized;
  media?: Media;
  order?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type FeedItem = {
  _id: string;
  _type: "feedItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "project" | "youtube" | "event" | "news";
  project?: ProjectReference;
  title?: Localized;
  description?: Localized;
  media?: Media;
  url?: string;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Localized;
  slug?: Slug;
  title?: Localized;
  description?: Localized;
  seo?: Seo;
  media?: Media;
  blocks?: Array<
    {
      _key: string;
    } & ContentBlock
  >;
  related?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  title?: Localized;
  description?: Localized;
  seo?: Seo;
  media?: Media;
  videoUrl?: string;
  status?: Localized;
  blocks?: Array<
    {
      _key: string;
    } & ContentBlock
  >;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  title?: Localized;
  description?: Localized;
  seo?: Seo;
  client?: string;
  year?: number;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  workCover?: Media;
  workPosition?: number;
  cover?: Media;
  blocks?: Array<
    {
      _key: string;
    } & ContentBlock
  >;
  website?: string;
  related?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  credits?: string;
  awards?: Array<string>;
  order?: number;
};

export type ContentBlock = {
  _type: "contentBlock";
  kind?:
    | "text"
    | "image"
    | "imagePair"
    | "imageText"
    | "video"
    | "gallery"
    | "quote"
    | "statement"
    | "spacer"
    | "credits";
  title?: Localized;
  text?: RichText;
  image?: Media;
  images?: Array<
    {
      _key: string;
    } & Media
  >;
  url?: string;
  quote?: Localized;
  attribution?: string;
  caption?: Localized;
  height?: number;
  credits?: Array<{
    name?: string;
    role?: Localized;
    _key: string;
  }>;
};

export type RichText = {
  _type: "richText";
  fr?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  es?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Overlay
  | SanityImageAssetReference
  | OverlayImage
  | Settings
  | Seo
  | Localized
  | SanityImageCrop
  | SanityImageHotspot
  | Offer
  | Media
  | Testimonial
  | ProcessStep
  | ProjectReference
  | FeedItem
  | Service
  | Slug
  | Page
  | ServiceReference
  | Project
  | ContentBlock
  | RichText
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_QUERY
// Query: { "settings": *[_type == "settings"][0]{...,"clients": clients[]{...,"icon":icon.asset->url}}, "projects": *[_type == "project" && defined(slug.current)] | order(order asc){...,"related": related[]._ref,"services": services[]->name}, "pages": *[_type == "page" && defined(slug.current)], "feed": *[_type == "feedItem"] | order(order asc){...,project->{slug,cover,title,description}}, "process": *[_type == "processStep"] | order(order asc), "testimonials": *[_type == "testimonial"] | order(order asc), "offers": *[_type == "offer"] | order(order asc), "services": *[_type == "service"] | order(order asc)}
export type SITE_QUERY_RESULT = {
  settings: {
    _id: string;
    _type: "settings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    siteName?: string;
    hero?: Localized;
    cta?: Localized;
    ctaSecondary?: Localized;
    processIntro?: Localized;
    processSubline?: Localized;
    callUrl?: string;
    whatsappUrl?: string;
    youtubeUrl?: string;
    toolsUrl?: string;
    email?: string;
    socials?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
    clients: Array<{
      name?: string;
      icon: string | null;
      _key: string;
    }> | null;
    videos?: Array<{
      title?: Localized;
      url?: string;
      _key: string;
    }>;
    defaultSeo?: Seo;
  } | null;
  projects: Array<{
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    title?: Localized;
    description?: Localized;
    seo?: Seo;
    client?: string;
    year?: number;
    services: Array<null> | ArrayOf<Localized> | null;
    workCover?: Media;
    workPosition?: number;
    cover?: Media;
    blocks?: Array<
      {
        _key: string;
      } & ContentBlock
    >;
    website?: string;
    related: Array<string> | null;
    credits?: string;
    awards?: Array<string>;
    order?: number;
  }>;
  pages: Array<{
    _id: string;
    _type: "page";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug?: Slug;
    title?: Localized;
    description?: Localized;
    seo?: Seo;
    media?: Media;
    videoUrl?: string;
    status?: Localized;
    blocks?: Array<
      {
        _key: string;
      } & ContentBlock
    >;
  }>;
  feed: Array<{
    _id: string;
    _type: "feedItem";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    kind?: "event" | "news" | "project" | "youtube";
    project: {
      slug: Slug | null;
      cover: Media | null;
      title: Localized | null;
      description: Localized | null;
    } | null;
    title?: Localized;
    description?: Localized;
    media?: Media;
    url?: string;
    order?: number;
  }>;
  process: Array<{
    _id: string;
    _type: "processStep";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: Localized;
    summary?: Localized;
    description?: Localized;
    time?: Localized;
    media?: Media;
    order?: number;
  }>;
  testimonials: Array<{
    _id: string;
    _type: "testimonial";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    person?: string;
    company?: string;
    role?: Localized;
    quote?: Localized;
    media?: Media;
    order?: number;
  }>;
  offers: Array<{
    _id: string;
    _type: "offer";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    price?: string;
    promise?: Localized;
    description?: Localized;
    weeks?: string;
    includes?: Array<
      {
        _key: string;
      } & Localized
    >;
    media?: Media;
    order?: number;
  }>;
  services: Array<{
    _id: string;
    _type: "service";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Localized;
    slug?: Slug;
    title?: Localized;
    description?: Localized;
    seo?: Seo;
    media?: Media;
    blocks?: Array<
      {
        _key: string;
      } & ContentBlock
    >;
    related?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
    order?: number;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n "settings": *[_type == "settings"][0]{...,"clients": clients[]{...,"icon":icon.asset->url}},\n "projects": *[_type == "project" && defined(slug.current)] | order(order asc){...,"related": related[]._ref,"services": services[]->name},\n "pages": *[_type == "page" && defined(slug.current)],\n "feed": *[_type == "feedItem"] | order(order asc){...,project->{slug,cover,title,description}},\n "process": *[_type == "processStep"] | order(order asc),\n "testimonials": *[_type == "testimonial"] | order(order asc),\n "offers": *[_type == "offer"] | order(order asc),\n "services": *[_type == "service"] | order(order asc)\n}': SITE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
